os:
  - linux
  - osx
language: java
addons:
  apt:
    packages:
      - gnome-keyring
      - gnome-session
before_script: 
  - if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then export DISPLAY=:99.0;  fi
  - if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then sh -e /etc/init.d/xvfb start;  fi
  - if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then sleep 3;  fi
  - if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then gnome-session; fi
script:
  - mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)