os:
  - linux
  - osx
sudo: required  
language: java
addons:
  apt:
    packages:
      - dbus
      - libdbus-glib-1-dev
      - gnome-keyring
      - gnome-desktop-testing 
      - dbus-x11
before_install:
  - if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then dbus-launch; nome-keyring-daemon with --unlock; fi  
script:
  - mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
