os:
  - linux
  - osx
sudo: required  
language: java
addons:
  apt:
    packages:
      - dbus
      - libdbus-glib-1-dev
      - libgnome-keyring0      
      - libsecret-tools
      - gnome-keyring
      - libgnome-keyring-dev
      - python-gnomekeyring
      - gir1.2-gnomekeyring-1.0 
before_script:
  - source .setupkeystore.sh
script:
  - mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
